/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package gloriacrud;

import java.sql.*;
import javax.swing.JOptionPane;

/**
 *
 * @author Student
 */
public class LogInForm extends javax.swing.JFrame {

    /**
     * Creates new form LogInForm
     */
    public LogInForm() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panel_mother = new javax.swing.JPanel();
        label_title = new javax.swing.JLabel();
        panel_username = new javax.swing.JPanel();
        label_username = new javax.swing.JLabel();
        tf_username = new javax.swing.JTextField();
        panel_password = new javax.swing.JPanel();
        label_password = new javax.swing.JLabel();
        pf_password = new javax.swing.JPasswordField();
        btn_login = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(27, 27, 27));

        panel_mother.setBackground(new java.awt.Color(26, 26, 26));

        label_title.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        label_title.setForeground(new java.awt.Color(243, 243, 243));
        label_title.setText("Log-in Form");

        panel_username.setBackground(new java.awt.Color(30, 30, 30));

        label_username.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        label_username.setForeground(new java.awt.Color(243, 243, 243));
        label_username.setText("Enter Username:");

        tf_username.setText("JonDoe123");

        javax.swing.GroupLayout panel_usernameLayout = new javax.swing.GroupLayout(panel_username);
        panel_username.setLayout(panel_usernameLayout);
        panel_usernameLayout.setHorizontalGroup(
            panel_usernameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_usernameLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(label_username, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(tf_username, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        panel_usernameLayout.setVerticalGroup(
            panel_usernameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_usernameLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panel_usernameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(label_username, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(tf_username))
                .addContainerGap(9, Short.MAX_VALUE))
        );

        panel_password.setBackground(new java.awt.Color(30, 30, 30));
        panel_password.setPreferredSize(new java.awt.Dimension(245, 40));

        label_password.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        label_password.setForeground(new java.awt.Color(243, 243, 243));
        label_password.setText("Enter Password:");

        pf_password.setText("jPasswordField1");

        javax.swing.GroupLayout panel_passwordLayout = new javax.swing.GroupLayout(panel_password);
        panel_password.setLayout(panel_passwordLayout);
        panel_passwordLayout.setHorizontalGroup(
            panel_passwordLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_passwordLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(label_password, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(pf_password, javax.swing.GroupLayout.PREFERRED_SIZE, 227, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(9, 9, 9))
        );
        panel_passwordLayout.setVerticalGroup(
            panel_passwordLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_passwordLayout.createSequentialGroup()
                .addGap(8, 8, 8)
                .addGroup(panel_passwordLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(label_password, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pf_password))
                .addContainerGap(7, Short.MAX_VALUE))
        );

        btn_login.setBackground(new java.awt.Color(51, 153, 255));
        btn_login.setForeground(new java.awt.Color(249, 249, 249));
        btn_login.setText("Log-in");
        btn_login.setBorderPainted(false);
        btn_login.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_loginActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panel_motherLayout = new javax.swing.GroupLayout(panel_mother);
        panel_mother.setLayout(panel_motherLayout);
        panel_motherLayout.setHorizontalGroup(
            panel_motherLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel_motherLayout.createSequentialGroup()
                .addContainerGap(325, Short.MAX_VALUE)
                .addComponent(btn_login)
                .addContainerGap())
            .addGroup(panel_motherLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(panel_motherLayout.createSequentialGroup()
                    .addContainerGap()
                    .addGroup(panel_motherLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(panel_motherLayout.createSequentialGroup()
                            .addComponent(label_title)
                            .addGap(0, 0, Short.MAX_VALUE))
                        .addComponent(panel_username, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(panel_password, javax.swing.GroupLayout.DEFAULT_SIZE, 391, Short.MAX_VALUE))
                    .addContainerGap()))
        );
        panel_motherLayout.setVerticalGroup(
            panel_motherLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel_motherLayout.createSequentialGroup()
                .addGap(144, 144, 144)
                .addComponent(btn_login, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(16, 16, 16))
            .addGroup(panel_motherLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(panel_motherLayout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(label_title)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(panel_username, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(panel_password, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(62, Short.MAX_VALUE)))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(panel_mother, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panel_mother, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_loginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_loginActionPerformed
        // TODO add your handling code here:
        String user = tf_username.getText();
        String pass = pf_password.getText();
        PreparedStatement preparedStatement = null;
        ResultSet resultSet = null;
        try{
            Connection connection = SQLConnector.getConnection();
//            Statement st = connection.createStatement();
            String select_query = String.format("SELECT * FROM user WHERE userName = ? AND userPassword = ?");
            preparedStatement = connection.prepareStatement(select_query);
            preparedStatement.setString(1, user);
            preparedStatement.setString(2, pass);
            resultSet = preparedStatement.executeQuery();
            
            if(resultSet.next()){
                this.dispose();
                UserMaintenance um = new UserMaintenance();
                um.setVisible(true);
            }else{
                JOptionPane.showMessageDialog(null, "Error: Invalid Username and/or Password");
            }
        }catch(SQLException e){
           JOptionPane.showMessageDialog(null, "Error" + e);
            
        }
    }//GEN-LAST:event_btn_loginActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LogInForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LogInForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LogInForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LogInForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LogInForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_login;
    private javax.swing.JLabel label_password;
    private javax.swing.JLabel label_title;
    private javax.swing.JLabel label_username;
    private javax.swing.JPanel panel_mother;
    private javax.swing.JPanel panel_password;
    private javax.swing.JPanel panel_username;
    private javax.swing.JPasswordField pf_password;
    private javax.swing.JTextField tf_username;
    // End of variables declaration//GEN-END:variables
}
